# Generated by Django 6.0 on 2025-12-19 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание категории"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="category/", verbose_name="Изображение категории"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=150, unique=True, verbose_name="URL"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Furniture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Артикул",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=150, unique=True, verbose_name="URL"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный товар"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Рекомендуемый"),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Материал"
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=100, verbose_name="Цвет"),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Габариты (В×Ш×Г)"
                    ),
                ),
                (
                    "weight",
                    models.CharField(blank=True, max_length=50, verbose_name="Вес"),
                ),
                (
                    "assembly_required",
                    models.BooleanField(default=True, verbose_name="Требуется сборка"),
                ),
                (
                    "warranty",
                    models.CharField(
                        default="5 лет", max_length=50, verbose_name="Гарантия"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="furniture/", verbose_name="Основное изображение"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="main.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["-created_at"],
            },
        ),
    ]
